name: Deploy PR previews

concurrency: preview-${{ github.ref }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
env:
  CARGO_TERM_COLOR: always

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run doc
      run: cargo doc --no-deps
    - name: Deploy PR Preview
      uses: rossjrw/pr-preview-action@v1.4.0
      with:
        source-dir: ./target/doc/
