name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose

  doc:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Run doc
      run: cargo doc --no-deps

    - name: Deploy PR Preview
      uses: rossjrw/pr-preview-action@v1.4.0
      with:
        source-dir: ./target/doc/


